# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Culture Lab Testing
short_labname: CL
email: ghdghd2015@snu.ac.kr
logo: logo.png
description: > # 다음 줄에 연구실 소개 입력
  Culture Lab 문화연구, Seoul National University; 서울대학교 언론정보학과 홍석경 교수 연구실; SK Hong;
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  minjunglalaa
google-site-verification:

# Build settings
markdown: kramdown
include: ['_pages', '_news']
plugins: [jekyll-seo-tag,jekyll-paginate]

paginate: 5
paginate_path: "/news/page:num/"
